### ISSUE TITLE
Hello Sir! I Have 0.012XMR In my Wallet But They are disappeared Now

### ISSUE THREAD

**Issue by Itsmtf** [mymonero/mymonero-app-site#25]
Hello Sir,
I want to know that my account automatically send 0.01XMR To Null Address(No Address).
Please Help me it took more than 1 month to mine 0.1 xmr or tell me where to contact I am Providing You All Proof. 
Transaction ID:
e95fda6f01a098cec93d557e0638c2af5f0ad7dbcfd6ccb268f838e1bf9b69b4
Transaction ID Image:-
![XMRR](https://user-images.githubusercontent.com/80289355/111537762-a8f99700-878d-11eb-9003-76a0459202e8.PNG)

Transaction Image:-
![XMR](https://user-images.githubusercontent.com/80289355/111537604-78196200-878d-11eb-9e54-a26dd2511295.PNG)

Please help Me!

**Comment by devinpearson** [comment]
Unfortunately, this means your private keys are no longer private and they have transferred your monero out of the wallet

**Comment by Itsmtf** [comment]
But How Can I Get This Amount Back. And It is not showing any address.

**Comment by Itsmtf** [comment]
And I How My Keys Shared While This Is My Personal PC With Original Windows. And Other Stuff.

**Comment by devinpearson** [comment]
Monero transactions are not reversible.  

The address will only show if you sent the transaction from your device. The monero blockchain stores addresses as stealth addresses and are not shown in the app

**Comment by devinpearson** [comment]
There is a high probability that your device has been compromised. the keys are encrypted on your drive and are never sent to the server
