### ISSUE TITLE
Website update for Linux user-agent

### ISSUE THREAD

**Issue by niclaz** [mymonero/mymonero-app-site#64]
Went to download the Linux edition of MyMonero and the website sent me to download 1.3.2 (August 2022 release)

All three buttons/links on the website point to the following:

`https://github.com/mymonero/mymonero-app-js/releases/download/v1.3.2/MyMonero-1.3.2.AppImage`

Went to look for the SHA256 hashes for the file and noticed that in the current release is 1.3.3

Requesting update of the webpage/link to the release. 

Thanks for an excellent product.

**Comment by devinpearson** [comment]
Thanks @niclaz! We will get that sorted out this week.

**Comment by niclaz** [comment]
Closed the issue that was still open but fixed

That said there is another update to be made - website points to 1.3.2 and 1.3.3 is available since Nov 2022

Maybe worth having the link of the website lead to the [general release overview page ](https://github.com/mymonero/mymonero-app-js/releases) of the app-js repo
