### ISSUE TITLE
Unable to transfer funds

### ISSUE THREAD

**Issue by mrmoo85** [mymonero/mymonero-app-site#9]
Hi

I am unable to get ahold of mymonero support, they are not responding to either email listed on their website. I am not sure if this is the right place to post a bug.

I have monero in my account but when I try to send I get error "Failed to decode address (#0): Invalid address prefix"

I think this is an issue with the code/server

> Address
> 486hiBt6zu5fJ9RvuHapFnJHPZ4zqtAChYvmVrs4NiLM1fonXAyHcwPhhqaZZwkTfXGNqwbKaLWag8uVBbGAwuMCKEEDDpg 
> 
> Transaction History
> Value (XMR)
> Date Received
> Mixin
> Transaction ID
> 0.054041224686
> 29 July 2018 05:55:09
> 6
> 91ae7f981acd2ad0a8fd835e68552ce750d36075388ca2cb81a95049f069546d

Can anyone help / look into this please?

Thanks

**Comment by paulshapiro** [comment]
Hey mrmoo85, did support get back to you? 

I'm actually not sure why you're experiencing that issue. It's not a subaddress. And I do not get a decode error when I run the address against mymonero/mymonero-core-js. We're 

We're also gonna have our new support system live pretty soon now so there will be a nicer way to get in touch.

We're at defcon at the moment but will deploy after.

For now, can you use the MyMonero desktop app? You can download it on our releases page.

(By the way, I'm curious, had you heard about the new app?)

Thanks

**Comment by mrmoo85** [comment]
No replies from support. I have checked my emails and spam. Live support is badly needed, especially when emails are not answered.

I will try using the desktop wallet but I swear it was windows only...

I have used the monero core wallet, but it is unable to import, and when it does it shows a 0 balance.
